version: '3'

services:
  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: web3platform
      POSTGRES_PASSWORD: password
      POSTGRES_DB: web3platform
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "web3platform"]
      interval: 10s
      timeout: 20s
      retries: 5
    ports:
      - "5432"
    volumes:
      - pg:/var/lib/postgresql/data
  migrate:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/migrate/Dockerfile
    working_dir: /app
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
    command: npm run db:migrate
  api:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/trpc/Dockerfile
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
        NEXT_PUBLIC_IS_MAINNET: "false"
        API_BUILD: "true"
    working_dir: /app
    ports:
      - "4000:3000"
    depends_on:
      - pg
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
      - CKB_EXPLORER_API_PREFIX=
      - AIRTABLE_BEARER_TOKEN=
      - AIRTABLE_BASE_ID=
      - CKB_RPC_URL=
  db-seed:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/db-seed/Dockerfile
    working_dir: /app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
      - AIRTABLE_BEARER_TOKEN=
      - AIRTABLE_BASE_ID=
    command: npm run db:seed
  aggregator-ckb:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/aggregator-ckb/Dockerfile
      args:
        NEXT_PUBLIC_IS_MAINNET: "false"
    working_dir: /app
    depends_on:
      db-seed:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
      - NEXT_PUBLIC_IS_MAINNET=false
      - START_BLOCK_NUMBER=
      - NODE_OPTIONS=--max-old-space-size=4096
      - CKB_RPC_URL=
      - AGGREGATOR_LOG_LEVEL=
      - PREPARATION_CONCURRENCY
      - AIRTABLE_BEARER_TOKEN
      - AIRTABLE_BASE_ID
  aggregator-btc:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/aggregator-btc/Dockerfile
    working_dir: /app
    depends_on:
      db-seed:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
      - START_BLOCK_NUMBER=
      - AGGREGATOR_LOG_LEVEL=
      - AGGREGATOR_PREPARATION_TIMEOUT=
      - PREPARATION_CONCURRENCY
  scheduled-task:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./devtools/scheduled-task/Dockerfile
    working_dir: /app
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      - DATABASE_URL=postgresql://web3platform:password@pg:5432/web3platform
      - COINMARKET_API_PREFIX=
      - COINMARKET_API_KEY=
      - UTXO_SWAP_API_PREFIX=
      - OMIGA_API_PREFIX=
      - AIRTABLE_BEARER_TOKEN
      - AIRTABLE_BASE_ID
volumes:
  pg:
