name: Pull, build docker image and push to repository

on:
  workflow_call:
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true
    outputs:
      # Image name
      image-name:
        description: URL for docker image
        value: ${{ jobs.build.outputs.image-name }}
      # Image tag (version)
      image-tag:
        description: image tag(version)
        value: ${{ jobs.build.outputs.image-tag }}
jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image-name: "${{ steps.set-image-info.outputs.IMAGENAME  }}"
      image-tag: "${{ steps.set-image-info.outputs.IMAGETAG  }}"
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Image Name & Image Tag
        id: set-image-info
        run: |
            echo "IMAGETAG=$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short=7 ${{ github.sha }})" >> $GITHUB_OUTPUT 
            echo "IMAGENAME=web3-platform" >> $GITHUB_OUTPUT 
            echo "IMAGEINFO=web3-platform:$(git rev-parse --abbrev-ref HEAD)-$(git rev-parse --short=7 ${{ github.sha }})" >> $GITHUB_ENV 
            
      - name: Docker login
        run: docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push image
        id: build_push__image
        run: |
          docker build -t ghcr.io/${{ secrets.GHCR_USERNAME }}/${IMAGEINFO}  -f  ./devtools/Dockerfile .
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/${IMAGEINFO}

      - name: DeleteUselessImages
        run: docker images && docker images| grep "web3-platform" | grep -v "IMAGE ID" | awk 'NR>1 {print $3}' | xargs -I {}  docker rmi {}

      - name: CheckImage
        run: docker images && df -hT && df -ih && echo ${{ steps.set-image-info.outputs.IMAGENAME  }}
