name: Deploy to stage

on:
  push:
    branches:
      - develop

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  deploy:
    needs: build
    uses: ./.github/workflows/update-image.yml
    with:
      k8s-namespace: web3-platform
      k8s-workload: -sta
      image-name: ${{ needs.build.outputs.image-name }}
      image-tag: ${{ needs.build.outputs.image-tag }}
    secrets: inherit